### PR TITLE
fix: Skip theme install if already exists. Closes #47

### LINKED ISSUE #47: When a recommended theme is already installed, and user selects to install it, causes the extension to hang
**Describe the bug**
User already has an installed theme that is being recommended and attempts to install it, this causes VS Code to hang

**Expected behaviour**
Don't recommend themes that a user already has installed

**Screenshots**
Video of problem: https://clips.twitch.tv/FrozenSaltyLarkImGlitch-KMy6nn5AJNDbCLbC

### PR DESCRIPTION
**Pull request by mtfoley**
This PR should fix #47. If the theme is already installed, show an information message indicating this. If it's not, run installation and reset `themeExtension` variable. In either case, proceed to activating the theme extension.

### CODE REVIEW

File: extension/src/installPrompt.ts [hunk 1]
```diff
@@ -40,19 +40,25 @@ export class InstallPrompt {
...
+            progress.report({ message: `Installing ${this.theme.name} theme...` });
+  
+            return new Promise((resolve) => {
+              vscode.extensions.onDidChange((e) => resolve(null));
+              vscode.commands.executeCommand("workbench.extensions.installExtension", this.theme.extensionName);
+            });
+          },
+        );
+        themeExtension = vscode.extensions.getExtension(this.theme.extensionName);  
+      } else {
```
Comment (MichaelJolley) [inline extension/src/installPrompt.ts:56]: Let's remove this informational message. I believe the next thing we do is set the theme. That's enough notification.

**Review by MichaelJolley — CHANGES_REQUESTED** [review]
Well done @mtfoley! Can you make this one small change and we'll get it merged.

File: extension/src/installPrompt.ts (hunk 1 above)
Comment (mtfoley) [reply extension/src/installPrompt.ts]: Updated

**Review by MichaelJolley — APPROVED** [review]

**Comment by MichaelJolley** [comment]
@all-contributors please add @mtfoley for code
